### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by tibetegya** [Rwothoromo/WeConnect-App#10]
https://github.com/Rwothoromo/WeConnect-App/blob/6d39c6c250600d3bd55e24ef03da027eb596b321/.travis.yml#L14

**Comment by tibetegya** [comment]
Hello could you please explain this line to me

**Comment by Rwothoromo** [comment]
@tibetegya the source switch tell coverage to run on the root directory of the project whereas omit tells which file/directory to skip.
